name: isura_system
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  shared_preferences: 2.0.5
  flutter_secure_storage: ^3.3.3
  get: 3.26.0
  cached_network_image: ^2.2.0+1
  date_format: ^2.0.2
  flutter_datetime_picker: ^1.5.0
  intl: 0.16.1
  image_picker_gallery_camera: ^0.1.6
  permission_handler: ^5.1.0+2
  unicons: ^1.0.1
  animated_splash_screen: ^1.0.1+2
  flutter_signin_button: ^2.0.0
  firebase_auth: 0.19.0
  firebase_core: 0.6.0
  cloud_firestore: 0.15.0
  firebase_storage: 6.0.0
  firebase_database: 5.0.0
  google_sign_in: 4.5.9
#  flutter_facebook_login: ^3.0.0
  flutter_launcher_icons: ^0.8.0
  flutter_downloader: ^1.5.0
  file_picker: 2.0.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdf/
